### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SubfieldBase'

### ISSUE THREAD

**Issue by ianmiell** [pinax/pinax-project-socialauth#8]
Any idea what I'm doing wrong? 

This:

```
FROM ubuntu
RUN apt-get update -y 
RUN apt-get install -y python-pip
RUN pip install --upgrade pip
RUN pip install pinax-cli
RUN pinax start --dev social-auth codetest
WORKDIR codetest
RUN chmod +x manage.py
RUN pip install -r requirements.txt
RUN ./manage.py migrate
RUN ./manage.py loaddata sites
RUN ./manage.py runserver
```

docker build ...

```
Step 12/14 : RUN ./manage.py migrate
 ---> Running in 80a0819c41a7
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/default/models.py", line 14, in <module>
    from social.apps.django_app.default.fields import JSONField
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/default/fields.py", line 14, in <module>
    class JSONField(six.with_metaclass(models.SubfieldBase, models.TextField)):
AttributeError: 'module' object has no attribute 'SubfieldBase'
```

**Comment by mcbuehler** [comment]
The models.SubfieldBase class was removed (in Django 1.8 I think). You might be able to solve this by upgrading to a newer Django version.
